##########################################
# Konfiguration allgemein Speicher
speicher:
  ip: 192.168.178.27


##########################################
# Konfiguration für logfile

logfile:
  startDatum: 03.09.2021
  pfadart: relativ
  #pfadart: absolut
  pfadrelativ: ../logfiles
  pfadabsolut: D:\SENEC\logfiles
  suffix: txt
  sortyear: yes
  sortmonth: yes
  writemode: w+
  rewrite: yes
  cronjob: no
  yester: no
  sleep: 1
  errorcount: 3

